# Generated by Django 5.2.7 on 2025-10-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('transport_safety', 'Transport Safety'), ('academic_performance', 'Academic Performance'), ('attendance', 'Attendance Issue'), ('behavior', 'Behavioral Incident'), ('health_wellness', 'Health & Wellness'), ('school_safety', 'School Safety'), ('financial', 'Financial Update'), ('system', 'System Notification'), ('achievement', 'Student Achievement'), ('parent_meeting', 'Parent Meeting Request')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('default_priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('emergency', 'Emergency')], default='medium', max_length=10)),
                ('default_expiry_hours', models.IntegerField(default=24, help_text='Default expiry in hours')),
                ('variables_help', models.TextField(blank=True, help_text='Available variables for this template')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('transport_safety', 'Transport Safety'), ('academic_performance', 'Academic Performance'), ('attendance', 'Attendance Issue'), ('behavior', 'Behavioral Incident'), ('health_wellness', 'Health & Wellness'), ('school_safety', 'School Safety'), ('financial', 'Financial Update'), ('system', 'System Notification'), ('achievement', 'Student Achievement'), ('parent_meeting', 'Parent Meeting Request')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('emergency', 'Emergency')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', max_length=12)),
                ('target_user_types', models.JSONField(blank=True, default=list, help_text="User types who should receive this alert (e.g., ['parent', 'teacher'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='If this alert is about a specific student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.student')),
                ('target_users', models.ManyToManyField(blank=True, help_text='Specific users who should receive this alert', related_name='alerts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_aler_alert_t_82e8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', 'status'], name='alerts_aler_priorit_bae0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertacknowledgement',
            unique_together={('alert', 'user')},
        ),
    ]
